site_name: Documentation
site_description: Documentation for k0rdent
site_author: Mirantis, Inc.

docs_dir: docs/
repo_name: k0rdent docs
repo_url: https://github.com/k0rdent/docs

copyright:
  Copyright &copy; 2025 The k0rdent authors | Documentation distributed under <a href="https://creativecommons.org/licenses/by/4.0/legalcode.txt">CC-BY-4.0</a>.
  -- <a href="#__consent">Change cookie settings</a>

theme:
  name: "material"
  highlightjs: true
  language: "en"
  custom_dir: docs/custom_theme

  favicon: img/k0rdent-logo-mark-inverted.svg
  logo: img/k0rdent-logo-horizontal-inverted.svg
  
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

  features:
    - toc.autohide
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.tracking   # Anchor tracking
    - toc.follow            # Sidebar is automatically scrolled so that the active anchor is always visible
    - search.suggest        # Search suggestions
    - search.highlight      # Search highlights all occurrences after following the link
    - content.action.edit
    - content.action.view
    - navigation.path       # Not working, for sponsors only
    - navigation.indexes
    # - navigation.tabs
    # - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/feedback.js

plugins:
  - search
  - ezglossary:
      section_config:
        - name: demo
          inline_refs: short
  - macros:
      j2_variable_start_string: "{{{"
      j2_variable_end_string: "}}}"
  - exclude:
      glob:
        - "*.etag"
        - Dockerfile.serve-dev
        - Makefile*
        - requirements_pip.txt
        - requirements.txt

nav:
  - Welcome to the k0rdent docs: index.md
  - k0rdent concepts:
    - Why k0rdent?: why-k0rdent.md
    - k0rdent architecture: k0rdent-architecture.md
  - QuickStarts:
    - quickstarts/index.md
    - Set up Management Node and Cluster: quickstarts/quickstart-1-mgmt-node-and-cluster.md
    - Configure and Deploy to AWS: quickstarts/quickstart-2-aws.md
    - Configure and Deploy to Azure: quickstarts/quickstart-2-azure.md
  - Administrator Guide:
    - Before you start: admin-before.md
    - Installing k0rdent: admin-installation.md
    - Prepare k0rdent to create child clusters on multiple providers: admin-prepare.md
    - Creating standalone clusters: admin-creating-clusters.md
    - Adopting clusters: admin-adopting-clusters.md
    - Hosted control planes: admin-hosted-control-planes.md
    - Troubleshooting AWS VPCs: admin-troubleshooting-aws-vpcs.md
    - Using and creating service templates: admin-service-templates.md
    - Creating multi-cluster services: admin-create-multiclusterservice.md
    - k0rdent Observability & FinOps: admin-kof.md
    - Upgrading k0rdent: admin-upgrading-k0rdent.md
    - k0rdent credentials management: admin-credentials.md
    - k0rdent Role Based Access Control (RBAC): admin-rbac.md
    - Backing up k0rdent: admin-backup.md
  - User Guide:
    - Creating clusters as a k0rdent user: user-create-cluster.md
    - Creating and adding services to clusters as a k0rdent user: user-create-service.md
    - Enabling drift detection: user-enable-drift-detection.md
  - k0rdent Templates Reference:
    - Introduction to k0rdent templates: template-intro.md
    - Removing predefined templates: template-predefined.md
    - Bring-your-own (BYO) templates: template-byo.md
    - Templates for Amazon Web Services: template-aws.md
    - Templates for Azure: template-azure.md
    - Templates for OpenStack: template-openstack.md
    - Templates for vSphere: template-vsphere.md
  - Known Issues:
    - EKS: known-issues-eks.md
  - Reference:
    - Glossary: glossary.md
  - Appendix:
    - Extended management configuration: appendix-extend-mgmt.md
    - Understanding the dry run: appendix-dryrun.md
    - Cloud provider credentials management in CAPI: appendix-providers.md
  - Contributing:
    - k0rdent documentation contributor's guide: k0rdent-documentation-contributors-guide.md
    - k0rdent documentation style guide: k0rdent-documentation-style-guide.md

markdown_extensions:
  - callouts
  - tables
  - pymdownx.details
  - pymdownx.highlight: {}
  - pymdownx.superfences: {}
  - pymdownx.inlinehilite: {}
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
      toc_depth: 3
  - def_list

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/k0rdent/kcm
      name: k0rdent on GitHub
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/k0rdent
      name: k0rdent on X
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/k0rdent.bsky.social
      name: k0rdent on BlueSky
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UChXQ6kbvjnAtdZAQpl7Fo4A
      name: k0rdent on YouTube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/k0rdent/
      name: k0rdent on LinkedIn
  version:
    provider: mike
    default: stable
  docsVersionInfo:
    k0rdentVersion: 0-1-0
    k0rdentDotVersion: 0.1.0
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/k0rdent/docs/issues/new" target="_blank" rel="noopener">feedback form</a>.